name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: api-solid

    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: sudo apt-get install -y postgresql-client

      - run: |
          echo "Waiting for PostgreSQL to be ready..."
          until pg_isready -h postgres -U docker; do
            sleep 1
          done
          echo "PostgreSQL is ready!"

      - run: npm ci
      - run: npm run test:e2e
        env:
          JWT_SECRET: "5c290df4306534d78b246fa8cdd693d7041d82d1ac0c457e8fe8f969316cbc40"
          DATABASE_URL: "postgresql://docker:docker@postgres:5432/api-solid?schema=public"